#!/usr/bin/env bash

# Poll for a certbot-style DNS01 challenge to become active:

if [ $# -ne 2 ]; then
  echo "Usage: $0 <domain> <nonce>" >&2
  exit 1
fi
domain="$1"; shift
nonce="$1"; shift

while [ 1 ] ; do
  dig @8.8.8.8 txt "$domain" | \
  tee /dev/tty | \
  grep -q "$nonce" && break || echo 'sleeping'
  sleep 10
done
